### ISSUE TITLE
decompile java simple class failed

### ISSUE THREAD

**Issue by QGB** [csanuragjain/ClassModifier#1]
```

E:\java\ClassModifier>""C:\Android\Studio\jre"/bin/java.exe" -jar "E:\java\ClassModifier\\ClassModifier.jar"
Process Handler - jar2dex E:\java\ClassModifier\Projects\Main.class\classFile\Main.class -> E:\java\ClassModifier\Projects\Main.class\tobeProcessed\temp.dex
Process Handler - call com.android.dx.command.Main.main[--dex, --no-strict, --output=E:\java\ClassModifier\Projects\Main.class\tobeProcessed\temp.dex, E:\java\ClassModifier\Projects\Main.class\classFile\Main.class]
Process Handler -
Process Handler - UNEXPECTED TOP-LEVEL EXCEPTION:
Process Handler - java.lang.RuntimeException: Exception parsing classes
Process Handler -       at com.android.dx.command.dexer.Main.processClass(Main.java:752)
Process Handler -       at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
Process Handler -       at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
Process Handler -       at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
Process Handler -       at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)
Process Handler -       at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
Process Handler -       at com.android.dx.command.dexer.Main.processOne(Main.java:672)
Process Handler -       at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
Process Handler -       at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
Process Handler -       at com.android.dx.command.dexer.Main.run(Main.java:277)
Process Handler -       at com.android.dx.command.dexer.Main.main(Main.java:245)
Process Handler -       at com.android.dx.command.Main.main(Main.java:106)
Process Handler -       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Process Handler -       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Process Handler -       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Process Handler -       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Process Handler -       at com.googlecode.dex2jar.tools.Jar2Dex.doCommandLine(Jar2Dex.java:99)
Process Handler -       at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
Process Handler -       at com.googlecode.dex2jar.tools.Jar2Dex.main(Jar2Dex.java:32)
Process Handler -       at com.cooltrickshome.helper.RunProgramDex.changeClass2Dex(RunProgramDex.java:70)
Process Handler -       at com.cooltrickshome.helper.RunProgramDex.main(RunProgramDex.java:40)
Process Handler - Caused by: com.android.dx.cf.iface.ParseException: InvokeDynamic not supported
Process Handler -       at com.android.dx.cf.cst.ConstantPoolParser.determineOffsets(ConstantPoolParser.java:226)
Process Handler -       at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:132)
Process Handler -       at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)
Process Handler -       at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)
Process Handler -       at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)
Process Handler -       at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
Process Handler -       at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
Process Handler -       at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
Process Handler -       at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
Process Handler -       at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
Process Handler -       at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
Process Handler -       at com.android.dx.command.dexer.Main.processClass(Main.java:749)
Process Handler -       ... 20 more
Process Handler - 1 error; aborting






```
the Main.class source:

```
import java.lang.*;

public class Main {
    public static void main(String... args) {
		
        StringBuilder sb = new StringBuilder("Welcome to  ");
		sb.append(true);
		sb.append(1);
		long lo=2;
		sb.append(lo);
		
        System.out.println("qgb :"+sb.toString() );
    }
}
```

**Comment by QGB** [comment]
[source.zip](https://github.com/csanuragjain/ClassModifier/files/8926717/source.zip)

**Comment by QGB** [comment]
![image](https://user-images.githubusercontent.com/8005654/174280825-1d60c969-d7db-4abe-8d20-3295e54b2d1e.png)
![image](https://user-images.githubusercontent.com/8005654/174280922-d6d68087-4d56-4090-ad89-bc0546ef654c.png)
